-- =============================================================================
-- Moved.
--
-- The schema and seed data that used to live here are now in
-- setup\04-customer-feedback-data.sql (deployed by
-- setup\05-deploy-customer-feedback-data.ps1).
--
-- The procedures are in setup\06-chat-procedures.sql (deployed by
-- setup\07-deploy-chat-procedures.ps1).
--
-- The demo runner is demo\03-summarise-and-inject.ps1 — it adds the
-- prompt-injection feedback row at runtime so the defended proc can be
-- shown working perfectly first.
-- =============================================================================
